# Generated by Django 6.0.3 on 2026-04-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_files_processed", models.BigIntegerField(default=0)),
                ("total_storage_processed", models.BigIntegerField(default=0)),
            ],
        ),
    ]
