# Generated by Django 6.0.3 on 2026-03-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="properties",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
