# Generated by Django 6.0.3 on 2026-04-17 14:28

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="installed_year",
        ),
        migrations.RemoveField(
            model_name="line",
            name="diameter",
        ),
        migrations.RemoveField(
            model_name="line",
            name="line_name",
        ),
        migrations.RemoveField(
            model_name="line",
            name="line_type",
        ),
        migrations.RemoveField(
            model_name="line",
            name="material",
        ),
        migrations.RemoveField(
            model_name="node",
            name="node_name",
        ),
        migrations.RemoveField(
            model_name="node",
            name="node_type",
        ),
        migrations.RemoveField(
            model_name="project",
            name="utility_type",
        ),
        migrations.AddField(
            model_name="asset",
            name="external_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="global_id",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.project"
            ),
        ),
        migrations.AlterField(
            model_name="line",
            name="end_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incoming_lines",
                to="api.node",
            ),
        ),
        migrations.AlterField(
            model_name="line",
            name="properties",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="line",
            name="start_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outgoing_lines",
                to="api.node",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="properties",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("area_type", models.CharField(blank=True, max_length=100)),
                ("properties", models.JSONField(blank=True, default=dict)),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area",
                        to="api.asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "geometry_type",
                    models.CharField(
                        choices=[
                            ("Point", "Point"),
                            ("LineString", "LineString"),
                            ("Polygon", "Polygon"),
                        ],
                        max_length=50,
                    ),
                ),
                ("schema", models.JSONField(default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_types",
                        to="api.project",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.assettype",
            ),
        ),
        migrations.CreateModel(
            name="DatasetVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.project"
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.datasetversion",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="api.datasetversion",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["project", "version"], name="api_asset_project_ac6421_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["external_id"], name="api_asset_externa_8d1149_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="datasetversion",
            unique_together={("project", "version")},
        ),
    ]
