# Generated by Django 6.0.3 on 2026-04-18 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_asset_installed_year_remove_line_diameter_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assettype",
            name="project",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="asset_type",
        ),
        migrations.AlterField(
            model_name="asset",
            name="global_id",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
        migrations.CreateModel(
            name="Layer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "geometry_type",
                    models.CharField(
                        choices=[
                            ("Point", "Point"),
                            ("LineString", "LineString"),
                            ("Polygon", "Polygon"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("schema", models.JSONField(default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layers",
                        to="api.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="asset",
            name="layer",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.layer"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["layer"], name="api_asset_layer_i_03ab14_idx"),
        ),
        migrations.DeleteModel(
            name="AssetType",
        ),
        migrations.AlterUniqueTogether(
            name="layer",
            unique_together={("project", "name")},
        ),
    ]
