# Generated by Django 6.0.3 on 2026-03-28 06:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_node_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='utility_type',
        ),
        migrations.AddField(
            model_name='asset',
            name='installed_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='elevation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='node_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='node_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='utility_type',
            field=models.CharField(blank=True, choices=[('water', 'Water'), ('electricity', 'Electricity'), ('irrigation', 'Irrigation'), ('sewerage', 'Sewerage')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.project'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.project'),
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('line_name', models.CharField(blank=True, max_length=255, null=True)),
                ('line_type', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=50)),
                ('diameter', models.FloatField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='line', to='api.asset')),
                ('end_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_lines', to='api.node')),
                ('start_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_lines', to='api.node')),
            ],
        ),
        migrations.DeleteModel(
            name='Pipe',
        ),
    ]
