# Generated by Django 6.0.3 on 2026-04-18 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_layer_unique_together_layer_dataset_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="area",
                to="api.asset",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="layer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.layer"
            ),
        ),
        migrations.AlterField(
            model_name="line",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line",
                to="api.asset",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="node",
                to="api.asset",
            ),
        ),
    ]
