# Generated by Django 6.0.3 on 2026-04-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_study", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="casestudy",
            old_name="main_image",
            new_name="image",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="money_tag",
        ),
        migrations.AddField(
            model_name="casestudy",
            name="is_highlight",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="case_studies", to="case_study.casetag"
            ),
        ),
    ]
