# Generated by Django 6.0.3 on 2026-04-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_study", "0002_rename_main_image_casestudy_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestudy",
            name="is_highlight",
            field=models.BooleanField(default=False),
        ),
    ]
