# Generated by Django 6.0.3 on 2026-04-13 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case_study", "0003_alter_casestudy_is_highlight"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="casestudy",
            options={"ordering": ["-created_at"]},
        ),
    ]
